services:
  api:
    build: api/
    env_file:
      - api/.env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:alpine
    env_file:
      - api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  web:
    build: web/
    env_file:
      - web/.env
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres-db:
