services:
  # web:
  #   build: api/
  #   env_file:
  #     - api/.env
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - db

  db:
    image: postgres:alpine
    env_file:
      - api/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
